"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from decouple import config, Csv

# BASE_DIR ahora es un Path, no un string
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure-@*36+4euz3fn))iw9xl-qg93@n4plct1dq*y-#pxs7$dhf2v1r")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Tus apps
    "apps.usuarios",
    "apps.foro",
    "apps.podcast",
    "apps.agenda",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # usa Path
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Contexto personalizado (WhatsApp, etc.)
                "config.context_processors.whatsapp",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",  # ya funciona con Path
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# settings.py
AUTH_USER_MODEL = 'usuarios.CustomUser'


# Internationalization
LANGUAGE_CODE = 'es'
USE_I18N = True

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
    # Agrega más idiomas aquí
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('it', 'Italiano'),
    # etc.
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = "UTC"

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # carpeta para archivos estáticos en desarrollo
STATIC_ROOT = BASE_DIR / "staticfiles"   # para collectstatic en producción

# Media files (subidas de usuarios)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Mapear niveles de mensajes de Django a clases de Bootstrap
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',  # asegura alerta roja
}

# =============================
# Configuración de WhatsApp Help
# =============================
# Establece el número en formato internacional sin + ni espacios, ej: 573001112233
# Puedes sobrescribirlo con una variable de entorno WHATSAPP_SUPPORT_NUMBER
WHATSAPP_SUPPORT_NUMBER = os.getenv("WHATSAPP_SUPPORT_NUMBER", "573133169313")
# Mensaje por defecto que se pre-llena al abrir el chat (puede sobrescribirse por env)
WHATSAPP_DEFAULT_MESSAGE = os.getenv("WHATSAPP_DEFAULT_MESSAGE", "Hola, necesito ayuda con Iterum.")
# Habilitar/deshabilitar el popup de ayuda (puede sobrescribirse por env)
WHATSAPP_HELP_ENABLED = os.getenv("WHATSAPP_HELP_ENABLED", "True").lower() in {"1","true","yes","on"}

# =============================
# Moderación de contenido (Comentarios)
# =============================
# Backend por defecto: "local" (usa listas y regex). Opcional: "azure" (Content Safety)
MODERATION_BACKEND = os.getenv("MODERATION_BACKEND", "local").lower()
# Placeholders para Azure (si se habilita)
AZURE_CONTENT_SAFETY_ENDPOINT = os.getenv("AZURE_CONTENT_SAFETY_ENDPOINT", "")
AZURE_CONTENT_SAFETY_KEY = os.getenv("AZURE_CONTENT_SAFETY_KEY", "")
AZURE_CONTENT_SAFETY_CATEGORIES = (
    os.getenv("AZURE_CONTENT_SAFETY_CATEGORIES", "Hate,Sexual,Violence,SelfHarm").split(",")
)
# 0: Safe, 1: Low, 2: Medium, 3: High, 4: VeryHigh
AZURE_CONTENT_SAFETY_THRESHOLD = int(os.getenv("AZURE_CONTENT_SAFETY_THRESHOLD", "2"))

# =============================
# Palabras extra para el filtro local (por idioma)
# =============================
# Ejemplo: {"es": ["pirobo","piroba"], "en": ["dummy"]}
EXTRA_BANNED_WORDS = {
    "es": ["pirobo", "piroba"],
}

# =============================
# Configuración de Email (Gmail)
# =============================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='Iterum.comunidadhombres@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='tfln svow zqlc axtv')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER', default='Iterum.comunidadhombres@gmail.com')
