# Generated by Django 5.2.6 on 2025-09-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
