# Generated by Django 5.2.6 on 2025-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_bio_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
