# Generated by Django 5.2.7 on 2025-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_phone_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('like', 'Like'), ('comentario', 'Comentario'), ('respuesta', 'Respuesta'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
