# Generated by Django 5.2.6 on 2025-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
