# Generated by Django 5.2.7 on 2025-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_evento_descripcion_corta_evento_imagen_evento_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
