# Generated by Django 5.2.7 on 2025-11-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_eventocomentario_parent_eventolikecomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_virtual',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='plataforma_virtual',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
