# Generated by Django 5.2.7 on 2025-11-10 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_evento_latitud_evento_link_virtual_evento_longitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventofoto',
            name='hash_md5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='eventofoto',
            index=models.Index(fields=['evento', 'hash_md5'], name='agenda_even_evento__2f52bd_idx'),
        ),
    ]
